clear all;
close all;
fclose('all');
clc;

% sourcepath = {'C:\Users\delmo\Desktop\AM paper\Energy Fluence Spectra\Proton 14.5 MeV\XLSX', ...
%     'C:\Users\delmo\Desktop\AM paper\Energy Fluence Spectra\Proton 15.5 MeV\XLSX', ...
%     'C:\Users\delmo\Desktop\AM paper\Energy Fluence Spectra\Proton 16.5 MeV\XLSX'};
% sourcepath = {'C:\Users\delmo\Desktop\AM paper\Energy Fluence Spectra\Lid Parafilm\XLSX'};
% sourcepath = {'C:\Users\delmo\Desktop\AM paper\Energy Fluence Spectra\Proton 15.5 MeV\XLSX Lid v2', ...
%     'C:\Users\delmo\Desktop\AM paper\Energy Fluence Spectra\Proton 15.5 MeV\XLSX Parafilm v2', ...
%     'C:\Users\delmo\Desktop\AM paper\Energy Fluence Spectra\Proton 15.2 MeV Water target\XLSX', ...
%     'C:\Users\delmo\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV 103.1 cm Dist\Para\XLSX', ...
%     'C:\Users\delmo\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV 103.1 cm Dist\Lid\XLSX'};
% sourcepath = { ...
%     'C:\Users\delmo\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV 103.1 cm Dist\Para\XLSX', ...
%     'C:\Users\delmo\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV 103.1 cm Dist\Lid\XLSX'};
sourcepath = { ...
    'C:\Users\Delmon Arous\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV\v1\Pos 1 103.1 cm Parafilm\XLSX', ...
    'C:\Users\Delmon Arous\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV\v2\Pos 2 95.2 cm Lid\XLSX', ...
    'C:\Users\Delmon Arous\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV\v2\Pos 3 98.5 cm Lid\XLSX', ...
    'C:\Users\Delmon Arous\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV\v2\Pos 4 101.1 cm Lid\XLSX', ...
    'C:\Users\Delmon Arous\OneDrive - Universitetet i Oslo\PhD\AM paper\Energy Fluence Spectra\Proton 15.22 MeV\v2\Pos 5 103.1 cm Lid\XLSX'}; 

% str_E = {'14.5 MeV protons', '15.5 MeV protons', '16.5 MeV protons'};
% str_dist = {'30 cm', '40 cm', '50 cm', '60 cm', '70 cm', '80 cm', ...
%     '90 cm', '100 cm', '110 cm', '120 cm', '130 cm'};
% str = {'15.0 MeV - Lid', '15.0 MeV - Parafilm', ...
%     '15.5 MeV - Lid', '15.5 MeV - Parafilm', ...
%     '16.0 MeV - Lid', '16.0 MeV - Parafilm', ...
%     '16.5 MeV - Lid', '16.5 MeV - Parafilm'};
% str = {'70 cm', '80 cm', '90 cm'};
str = {'15.22 MeV protons, Pos 1: 103.1 cm Parafilm', ...
    '15.22 MeV protons, Pos 2: 95.2 cm Lid', ...
    '15.22 MeV protons, Pos 3: 98.5 cm Lid', ...
    '15.22 MeV protons, Pos 4: 101.1 cm Lid', ...
    '15.22 MeV protons, Pos 5: 103.1 cm Lid'};
str_detectors = {{'Transmission chamber, 1st half', ...
    'Transmission chamber, 2nd half', 'IC foil', 'Parafilm'}, ...
    {'Transmission chamber, 1st half', ...
    'Transmission chamber, 2nd half', 'IC foil', 'Lid'}, ...
    {'Transmission chamber, 1st half', ...
    'Transmission chamber, 2nd half', 'IC foil', 'Lid'}, ...
    {'Transmission chamber, 1st half', ...
    'Transmission chamber, 2nd half', 'IC foil', 'Lid'}, ...
    {'Transmission chamber, 1st half', ... 
    'Transmission chamber, 2nd half', 'IC foil', 'Lid'}};

% lineSpec_data = {'or', 'og', 'ob', 'oc', 'om', 'ok', 'oy', ...
%     '*r', '*g', '*c', '*m', '*k', '*y'};
% lineSpec_fit = {'-r', '-g', '-b', '-c', '-m', '-k', '-y', ...
%     '--r', '--g', '--c', '--m', '--k', '--y'};
lineSpec_data = {'-r', '-g', '-b', '-c', '-m', '-k', '-y'};
lineSpec_fit = {'-r', '--r', '-g', '--g', '-b', '--b', '-c', '--c'};

ndetectors = 4;
nbins = 600;

% sourcepath = 'C:\Users\delmo\OneDrive - Universitetet i Oslo\PhD\FLUKA Monte Carlo\X-ray 220 keV\Energy Fluence Spectra';
% filename = 'USRTRACK1.xlsx';
% 
% str = {'1.52 mm Al + 0.70 mm Cu filter', 'No filter'};
% ndetectors = 2;
% nbins = 400;
% 
% plotEnergyFluence(sourcepath, filename, str, ndetectors, nbins)

for i = 1:length(sourcepath)
    
    fileList = getAllFiles(sourcepath{i});
    
%     str_dist = {'30 cm', '40 cm', '50 cm', '60 cm', '70 cm', '80 cm', ...
%     '90 cm', '100 cm', '110 cm', '120 cm', '130 cm'};
    
%     figure();
%     hold on
    for j = 1:length(fileList)
        
        [filepath, filename, ext] = fileparts(fileList{j});
        [E, dPhi, dPhi_fit, mu] = ...
            readEnergyFluence(fullfile(filepath, [filename ext]), ...
            ndetectors, nbins);
        mu
        figure();
        hold on
        for k = 1:ndetectors
            plot(E(:,k), dPhi(:,k), lineSpec_data{k})
%             plot(E(:,k), dPhi_fit(:,k), lineSpec_fit{j})
            str_detectors{i}{k} = [str_detectors{i}{k} ...
                ' (' num2str(round(mu(k),2)) ' MeV)'];
        end
        hold off
        ylim([0 inf])
        xlabel('Energy (MeV)')
        ylabel('Relative fluence (#/cm^2/GeV)')
        lgd = legend(str_detectors{i}, 'Location', 'NorthWest'); % str_dist
        title(lgd, str{i}) % str_E{i}
        set(gca, 'FontSize', 14)
        
    end
%     hold off
%     ylim([0 inf])
%     xlabel('Energy (MeV)')
%     ylabel('Relative fluence (#/cm^2/GeV)')
%     lgd = legend(str_detectors, 'Location', 'NorthWest'); % str_dist
%     title(lgd, str{i}) % str_E{i}
%     set(gca, 'FontSize', 14)
    
end
